apiVersion: v1
kind: Secret
metadata:
  name: common-secret
  namespace: dg0416-lifesub-ns
type: Opaque
stringData:
  # 공통 보안 정보 (POSTGRES 제거)
  POSTGRES_PASSWORD: "Hi5Jessica!"
  JWT_SECRET_KEY: "7K7ldo51SaUGR8VfafOE3/LNgAhD4IKQKuRgIe/MFGXuED3/shSewRQ5U5WVzX5CRG5PhldnoUiOcCW5+GKheQ=="

---
apiVersion: v1
kind: Secret
metadata:
  name: member-secret
  namespace: dg0416-lifesub-ns
type: Opaque
stringData:
  # Member 서비스 보안 정보
  POSTGRES_PASSWORD: "Hi5Jessica!"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysub-secret
  namespace: dg0416-lifesub-ns
type: Opaque
stringData:
  # MySub 서비스 보안 정보
  POSTGRES_PASSWORD: "Hi5Jessica!"

---
apiVersion: v1
kind: Secret
metadata:
  name: recommend-secret
  namespace: dg0416-lifesub-ns
type: Opaque
stringData:
  # Recommend 서비스 보안 정보
  POSTGRES_PASSWORD: "Hi5Jessica!"
